### ISSUE TITLE
Nginx server runs OK but I can't map my local index.html file to nginx

### ISSUE THREAD

**Issue by rabit1** [f69m/docker-ubuntu32-nginx#1]
Hi, 

I have a 32bit ubuntu 14.04 server (192.168.1.201) and successfully pull and run this docker image. I can access the nginx welcome page from other computer. However, having mapped the local directory /var/www using this docker command:

docker run -d --name nginx -p 8080:80 -v /var/www/:/usr/share/nginx/html:ro f69m/ubuntu32-nginx

nginx can't seem to serve my /var/www/index.html page. Trying to access this index.html from other computer gives me a 404 error message. How do I troubleshoot this? 

http://192.168.1.201:8080       -> works (nginx welcome page)
http://192.168.1.201:8080/index.html     -> 404 Error. (Instead of my index.html page)

Sorry for this newbie question. Appreciate any help. Thank you,
Regards,

**Comment by f69m** [comment]
Sorry for the late response, seems I missed the notification.
The web root directory should be /var/www/html. Does it work, if you move your index file to /var/www/html/index.html?
If it won't work that way, I need to dig in deeper.

**Comment by rabit1** [comment]
That works. Thank you.
